name: Create new release with changelog

permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      semantic_version_update_source:
        description: "Choose which version should be updated"
        required: true
        default: from_label
        type: string
  workflow_dispatch:
    inputs:
      semantic_version_update_source:
        description: "Choose which version should be updated"
        required: true
        type: choice
        default: from_label
        options:
          - from_label
          - patch
          - minor
          - major
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Check release label
        id: release-label
        uses: getindata/action-release-label@v1.3.0
        if: ${{ github.event.pull_request.merged == true || (github.event.workflow_dispatch) }}

      - name: Get latest tag
        id: latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        with:
          semver_only: true

      - name: Join tags
        id: tag-bump
        env:
          A: ${{steps.release-label.outputs.level}}
          B: ${{inputs.semantic_version_update_source}}
        run: if [[ $B == from_label ]]; then echo bump=$A >> "$GITHUB_OUTPUT"; else echo bump=$B >> "$GITHUB_OUTPUT"; fi

      - name: Bump semantic version
        id: bump-semver
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          current_version: ${{ steps.latest-tag.outputs.tag }}
          level: ${{ steps.tag-bump.outputs.bump }}

      - name: Create release
        if: ${{ steps.bump-semver.outputs.new_version != null }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create --generate-notes --latest "${{ steps.bump-semver.outputs.new_version }}"

      - name: Add PR comment
        id: pr-comment
        uses: actions-ecosystem/action-create-comment@v1
        if: ${{ steps.bump-semver.outputs.new_version != null && github.event.pull_request == true }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          body: |
            The new version [${{ steps.bump-semver.outputs.new_version }}](https://github.com/${{ github.repository }}/releases/tag/${{ steps.bump-semver.outputs.new_version }}) has been released :tada:
